Exit challenger service
leapdao/challenge-services pull request #15
Opened 2020-03-23 12:46 UTC by roleengineer

Solves https://github.com/leapdao/meta/issues/119

2020-03-23 15:28 UTC, troggy commented on README.md
> +Each tool has it's own subdirectory with own README file and the whole codebase to run tools independently of each over or together, depends on your needs.
```suggestion
Each tool is in its own subdirectory with README file. Tools can be run separately or together, depending on your needs.
```

2020-03-24 10:41 UTC, troggy requested changes
Proposed some changes to READMEs.

Question: why use bash scripts instead of nodejs scripts?

2020-03-24 14:28 UTC, roleengineer commented
> Question: why use bash scripts instead of nodejs scripts?
To be honest with u I haven't even thought about nodejs, I've started with crontab, but it doesn't satisfy requirements, then I've searched a bit, and written a bash script. So, there is no specific reason. I guess, I can rewrite with js, if you suggest, but is it needed? Anyway the process is running by OS.

2020-03-25 15:49 UTC, troggy commented on exit-challenger/src/event-receiver/index.js
> +  // _eventSignature below is Web3.utils.sha3("Submission(bytes32,uint256,address,bytes32,bytes32)")
❤️

2020-03-26 11:02 UTC, troggy commented on exit-challenger/src/event-receiver/index.js
> +  if (result) {
this never be false. `exitCheck` as per current implementation can either resolve to `1` or reject because of the runtime exception. If we want the process to resume after failed `exitCheck` we need to handle that exception (e.g. with `.catch(e => { /* handle */ })`)

2020-03-26 11:03 UTC, troggy commented on exit-challenger/src/event-receiver/index.js
> +  if (result) {
same as `exitCheck` above

2020-03-26 13:41 UTC, troggy commented on exit-challenger/src/exit-checker/index.js
> +async function exitCheck(_exit) {
duplicates plasmaChecker heavily. I suggest to replace with something like:

```js
async function exitCheck(_exit) {
  return require('../plasma-checker').plasmaCheck(_exit).catch(e => {
    if (e.message === 'Still no data available.') {
      console.log("I AM GOING TO SEND EXIT TO MIQ");
      await sendTaskToMaybeInvalidQueue(_exit);
    }
  });
}
```

2020-03-26 13:41 UTC, troggy commented on exit-challenger/src/exit-checker/index.js
> +async function exitCheck(_exit) {
this code is just an idea, not tested 👆

2020-03-26 13:42 UTC, troggy commented on exit-challenger/src/tasks-queues/index.js
> +  const job = await maybeInvalidQueue.add(_exit, {
```suggestion
  await maybeInvalidQueue.add(_exit, {
```

2020-03-26 13:42 UTC, troggy commented on exit-challenger/src/tasks-queues/index.js
> +  const job = await invalidExitsQueue.add(_task);
```suggestion
  await invalidExitsQueue.add(_task);
```

2020-03-26 13:42 UTC, troggy commented on exit-challenger/src/tasks-queues/index.js
> +  const job = await challengeTxsQueue.add(_task);
```suggestion
  await challengeTxsQueue.add(_task);
```

2020-03-26 13:45 UTC, troggy commented on exit-challenger/src/tasks-queues/index.js
> +  const job = await challengeTxsQueue.add(_task);
also these could be replaced with 

```js
async function sendTaskToCTQ(_task) {
  return challengeTxsQueue.add(_task);
}
```

no need to await as we are not using result and the outer function is `async` and we'll await on it anyway

2020-03-26 13:51 UTC, troggy commented on exit-challenger/src/tx-submitter/index.js
> +  nonceFromDB = parseInt(nonceFromDB, 10);
would this work? This way we get get rid on `nonceInfo`

```suggestion
  let nonceFromDB = await client.get("nonce");
  if (!nonceInfo) {
     await client.set("nonce", nonceFromBlockhain);
     nonceFromDB = nonceFromBlockhain;
  }
  nonceFromDB = parseInt(nonceFromDB, 10);
```

2020-03-26 13:59 UTC, roleengineer commented on exit-challenger/src/tx-submitter/index.js
> +  nonceFromDB = parseInt(nonceFromDB, 10);
yes. it would work.

2020-03-27 16:34 UTC, troggy approved these changes
🥦

- looked though the code
- Tested docker build on rinkeby testnet with:
  - valid exit
  - double spend

great work!

2020-03-27 16:51 UTC, merged